name: Railway Schedule

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options:
          - start
          - stop
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 21 * * *'

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop
        if: inputs.action == 'stop' || github.event.schedule == '0 21 * * *'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway service -s ${{ secrets.RAILWAY_SERVICE_ID }}
          railway down -y
          echo "Stopped"

      - name: Start
        if: inputs.action == 'start' || github.event.schedule == '0 5 * * *'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway service -s ${{ secrets.RAILWAY_SERVICE_ID }}
          railway up
          echo "Started"
